name: CI

on:
  push:
    branches: [main]  
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./RestaurantApi  # 

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies 
        run: dotnet restore ./RestaurantApi/RestaurantAPI.csproj

      - name: Build
        run: dotnet build --no-restore ./RestaurantApi/RestaurantAPI.csproj

      - name: Test
        run: dotnet test ./RestaurantApi/RestaurantAPI.csproj
